services:
  geoipupdate:
    image: maxmindinc/geoipupdate:latest
    environment:
      - GEOIPUPDATE_ACCOUNT_ID=${GEOIPUPDATE_ACCOUNT_ID}
      - GEOIPUPDATE_LICENSE_KEY=${GEOIPUPDATE_LICENSE_KEY}
      - GEOIPUPDATE_EDITION_IDS=GeoLite2-ASN GeoLite2-City GeoLite2-Country
      - GEOIPUPDATE_FREQUENCY=168 # Update every 7 days
    volumes:
      - geoip_data:/usr/share/GeoIP
    restart: always

  ipwhitelist:
    image: aprole/ip-whitelist
    build: .
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - geoip_data:/usr/share/GeoIP
    depends_on:
      - geoipupdate
    restart: always
volumes:
  geoip_data:
